version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
    ports:
      - "5432:5432"
